### PR TITLE
Memoize some rules to avoid exponential time in deep nesting

### PR DESCRIPTION
**Pull request by pablogsal**
Additionally, fix the script to calculate the nesting level using the
generated extension.

Closes: #37

### CODE REVIEW

**Comment by lysnikolaou** [comment]
What about `del_targets`?  Does something like `del <'a.a'*20>` parse normally?

**Comment by pablogsal** [comment]
> What about `del_targets`? Does something like `del <'a.a'*20>` parse normally?

I tried with:

del a.a.a.a.a......a.a (more than 4000) and seems to parse fine.

**Comment by pablogsal** [comment]
> What about `del_targets`? Does something like `del <'a.a'*20>` parse normally?

I tried and something like `f"del {'(' * nesting_depth}x,{'),' * nesting_depth}"` also has exponential time, so we need to memorize `del_targets` as well.

**Comment by pablogsal** [comment]
> Edit: I forgot something. Before we merge this, have you measured what the memory cost is for these changes?

It increased 0.62% parsing xxl.txt and 0.83% parsing `((((((((((((((((((((1))))))))))))))))))))`.

**Comment by pablogsal** [comment]
Checked also with the largest python file in the standard library (`Lib/test/test_socket.py`) and it increased the memory 1.58%.

**Comment by pablogsal** [comment]
Are you ok with these results for landing this? :)

**Comment by lysnikolaou** [comment]
How does it compare to the current parser now? Still a little bit ahead?

**Comment by pablogsal** [comment]
> How does it compare to the current parser now? Still a little bit ahead?

The speed seems untouched (maybe a bit faster due to the extra memoization) if you parse something that relies heavily on `target`, `del_target` or `star_targer` . It would be good if you could confirm these findings on your side when possible

**Comment by lysnikolaou** [comment]
> > How does it compare to the current parser now? Still a little bit ahead?
> 
> The speed seems untouched (maybe a bit faster due to the extra memoization) if you parse something that relies heavily on `target`, `del_target` or `star_targer` . It would be good if you could confirm these findings on your side when possible

Of course, I'm working on a bug-fix for #38 and I'll verify everything right afterwards. Shouldn't be long.

**Comment by lysnikolaou** [comment]
Oops! Sorry, accidentally pushed the wrong button.

**Comment by lysnikolaou** [comment]
Verified everything. My measurements are very similar to those by @pablogsal. Everything that was too difficult to parse before, can be parsed smoothly now. So let's land this.

**Comment by gvanrossum** [comment]
I confirmed the quadratic behavior as well, and the fix works. Land it.

**Comment by pablogsal** [comment]
> Any chance of also committing the script you used to plot the times? (In a separate PR if you need to clean it up first.)

I will make another PR once I clean it up a bit :)

**Comment by pablogsal** [comment]
Thanks for the reviews and the confirmation of the problem!

**Pull request merged**
