### PR TITLE
Propagate errors from the tokenizer

### PR DESCRIPTION
**Pull request by pablogsal**
Closes: #48

### CODE REVIEW

**Comment by gvanrossum** [comment]
Maybe add a test too?

**Comment by lysnikolaou** [comment]
It seems that this introduced a segfault in `test_fstring`.

**Comment by pablogsal** [comment]
> It seems that this introduced a segfault in `test_fstring`.

Humm....is because some error has happening in `test_fstring` and we were ignoring it?

**Comment by lysnikolaou** [comment]
There were some errors in `test_fstring` prior to this, which I was going to work on one of these days, but now it completely crashes.

**Pull request merged**
