### PR TITLE
Handle raw strings with r and R in action helper

### PR DESCRIPTION
**Pull request by isidentical**
This is hopefully the last fix we are going to need. Testing this (and the previous PRs) on top of PyPI now.

### CODE REVIEW

**Comment by isidentical** [comment]
Verified on the PyPI dataset, full behavioral roundtrip 👍🏻  (there are still empty "" string constants in joined str parts we can fix, but not a big problem).

**Review by lysnikolaou — APPROVED** [review]
LGTM!

**Comment by isidentical** [comment]
By the way @lysnikolaou, just to confirm, `fstring-grammar-rebased-after-sprint` is the latest branch right? (I've been merging my code there but now that I was looking into the branch list, there are a couple different rebase branches 🤔)

**Comment by lysnikolaou** [comment]
Yup, `fstring-grammar-rebased-after-sprint` was the latest one.

**Comment by pablogsal** [comment]
> Verified on the PyPI dataset, full behavioral roundtrip 👍🏻  (there are still empty "" string constants in joined str parts we can fix, but not a big problem).

Where the empty strings are coming from?

**Comment by isidentical** [comment]
> Where the empty strings are coming from?

Example:
```py
f"""\
{1}
"""
```

Tree difference:
```py
Module(
   body=[
      Expr(
         value=JoinedStr(
            values=[
               FormattedValue(
                  value=Constant(value=1),
                  conversion=-1),
               Constant(value='\n')]))],
   type_ignores=[])
```
```py
Module(
   body=[
      Expr(
         value=JoinedStr(
            values=[
               Constant(value=''), # <========================
               FormattedValue(
                  value=Constant(value=1),
                  conversion=-1),
               Constant(value='\n')]))],
```

**Pull request merged**
