### PR TITLE
Run CI in pegen branch as well

### PR DESCRIPTION
**Pull request by pablogsal**

### CODE REVIEW

**Comment by lysnikolaou** [comment]
This currently builds the Docs and runs the Docs tests on Travis. Shouldn't we deactivate those or Travis entirely?

**Comment by pablogsal** [comment]
> Shouldn't we deactivate those or Travis entirely?

Right, I assume we can only GitHub actions.

**Comment by gvanrossum** [comment]
Is this PR against master or pegen?

**Comment by lysnikolaou** [comment]
> Is this PR against master or pegen?

Pegen.

**Comment by pablogsal** [comment]
Ok, removed Travis and docs.

**Pull request merged**
