### PR TITLE
[WIP] Use pegen in compile

### PR DESCRIPTION
**Pull request by lysnikolaou**
There are some spots we missed during the initial integration.

### CODE REVIEW

**Comment by lysnikolaou** [comment]
Turns out `compile` wasn't using pegen and now that it does, we've got multiple test failures, mostly related to annotations not being supported and `single` input without a trailing newline failing to parse.

**Comment by pablogsal** [comment]
Oh wow, there are many new failures :(

There are a bunch of different error messages but on first sight I don't understand some of the other stuff is happening (like missing attributes from objects).

I suppose we would need to fix those before merging this in alpha6. Do we have open issues for all the different kind of new failures? @lysnikolaou @gvanrossum

**Comment by gvanrossum** [comment]
How can I help?

**Comment by pablogsal** [comment]
I suppose that the best course of action is analyzing the test failures present with the code of this PR, opening a new issue per group of failures (many failures seem to be the same underlying issue) and then we can work (individually or together) on each one of them.

We could left some of the "simple" ones for after the merge it we need to (like the error for the `print` call without parentheses).

**Comment by pablogsal** [comment]
After #102 we just need to centre here on the errors that appear from `compile`

**Comment by lysnikolaou** [comment]
I was just about to merge `pegen` here. I think that one significant failure we should look into is the grammar for `single` input. I'm sure it's going to need some changing, but the things I've tried so far do not work.

**Comment by gvanrossum** [comment]
Heh, I'm not even sure what I did -- I was going to merge master into pegen, not sure what even pythonrun-fix is. Let me do another merge (from a more recent master) and then I'll look into single_input.

**Comment by gvanrossum** [comment]
Oh wait, I resolved a merge conflict, thinking I was just merging #102 (hence my change to the PR title). I'll separately merge master into pegen.

**Comment by lysnikolaou** [comment]
What you did is fine. We should merge the `pegen` branch into this one every time a new PR gets merged, so that we see where we stand regarding test failures.

**Comment by lysnikolaou** [comment]
PS I feel like we could use some real time chat (not in a forum-like form), if you have time to work on this for the next few hours.

**Comment by gvanrossum** [comment]
> PS I feel like we could use some real time chat (not in a forum-like form), if you have time to work on this for the next few hours.

Good idea, I set up a Hangouts group.

**Comment by gvanrossum** [comment]
Ow, that's right. If I don't push a better fix later tonight, feel free to revert it.

**Comment by gvanrossum** [comment]
I pushed a better fix that issues the error in compile.c.

**Comment by gvanrossum** [comment]
Not sure why GitHub now declares it cannot be merged. Anyway, the test failures should be the same as before, but there's much less code in this branch (just two files that affect compile()).

**Comment by gvanrossum** [comment]
So it seems these are the test files that still have failing tests:

- test_codeop
- test_fstring
- test_syntax
- test_traceback

**Comment by lysnikolaou** [comment]
Only `test_codeop` remains. I don't think I have enough energy to have a look at it now. First things tomorrow morning.

**Comment by gvanrossum** [comment]
> This probably needs a review.

Hopefully @pablogsal can do it, since he did the f-string support (for pegen) in the first place.

> PS I feel that when we're done with this and all of the followup little things things we wanna do, I really want to work on proper (f)string tokenization, which would allow removing all these hacks.

That would be great. It would require major sorcery to the tokenizer though, since we'd have all these new, context-sensitive tokens, like

- `"... {"`
- `} ... {`
- `} ..."`

The tokenizer will need a new kind of stack to know what kind of closing quote to expect, for example.

**Pull request merged**
