### PR TITLE
Compress data/xxl.py and decompress on demand

### PR DESCRIPTION
**Pull request by pablogsal**

### CODE REVIEW

**Comment by pablogsal** [comment]
> +9 −100,006 

These are the best PRs :wink:

**Comment by lysnikolaou** [comment]
And maybe also to `.gitignore`?

**Comment by pablogsal** [comment]
Done!

**Comment by lysnikolaou** [comment]
Should we move everything out of `Tools/peg_generator/.gitignore` to `.gitignore` maybe?

**Comment by pablogsal** [comment]
> Should we move everything out of `Tools/peg_generator/.gitignore` to `.gitignore` maybe?

Oh, I missed the existence of `Tools/peg_generator/.gitignore` (maybe because is hidden :P). Maybe better I should move the new ignore to `Tools/peg_generator/.gitignore` to keep things more organized. What do you think?

**Comment by lysnikolaou** [comment]
> What do you think?

Sounds reasonable. Let's do that! Thanks!

**Pull request merged**
