### PR TITLE
Refactor illegal syntax rules to avoid false positives

### PR DESCRIPTION
**Pull request by lysnikolaou**
This is needed to avoid unrelated `SyntaxError`'s having specialized error messages like:

```
>>> a = +
  File "<stdin>", line 1
    a = +
         ^
SyntaxError: cannot assign to name
>>> a: =
  File "<stdin>", line 1
    a: =
       ^
SyntaxError: illegal target for annotation
>>> def f(*a, **b): pass
... 
>>> f(a := )
  File "<stdin>", line 1
    f(a := )
           ^
SyntaxError: cannot use assignment expressions with name
```

### CODE REVIEW

**Comment by lysnikolaou** [comment]
> One minor question, do we want `expression` on the right-hand side or something more general?

Not sure. What would you propose for something like `f(a() := for)`? At the moment, it's illegal syntax.

**Comment by pablogsal** [comment]
> Not sure. What would you propose for something like `f(a() := for)`? At the moment, pegen outputs `illegal syntax` and the current parser also does so.

Meh, then let's focus on reproducing just what the old parser does and let's thing about further improvements later.

**Comment by pablogsal** [comment]
Hummm, it seems that there is a bunch of (new?) errors in `test fstring`:

```
======================================================================
FAIL: test_invalid_string_prefixes (test.test_fstring.TestCase) (str="fb''")
----------------------------------------------------------------------
  File "<string>", line 1
SyntaxError: unknown parsing error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/test/test_fstring.py", line 29, in assertAllRaise
    eval(str)
AssertionError: "invalid string prefix" does not match "unknown parsing error (<string>, line 1)"
```

**Comment by lysnikolaou** [comment]
> Hummm, it seems that there is a bunch of (new?) errors in `test fstring`:
> 
> ```
> ======================================================================
> FAIL: test_invalid_string_prefixes (test.test_fstring.TestCase) (str="fb''")
> ----------------------------------------------------------------------
>   File "<string>", line 1
> SyntaxError: unknown parsing error
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/runner/work/cpython/cpython/Lib/test/test_fstring.py", line 29, in assertAllRaise
>     eval(str)
> AssertionError: "invalid string prefix" does not match "unknown parsing error (<string>, line 1)"
> ```

Yes, that's expected. I've got a PR in the making, in order to fix all of these after my latest upstream PR was merged, but I'm waiting till https://bugs.python.org/issue40267 is also resolved.

**Comment by lysnikolaou** [comment]
Can I merge this?

**Comment by gvanrossum** [comment]
LGTM, go ahead.

**Pull request merged**
